### ISSUE TITLE
Support for the Retry-After header

### ISSUE THREAD

**Issue by acdha** [johnkpaul/jquery-ajax-retry#10]
HTTP 503s can have a `Retry-After` header suggesting how long to wait before retrying:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.37 

It seems like this could be naturally added to the jqXHR.timeout check as either a default or simply overriding the jqXHR value (I'm inclined towards the latter since the people who are careful enough to set the `Retry-After` header probably have good reasons for doing so).

**Comment by johnkpaul** [comment]
@acdha I had no idea that header existed. I agree that this would be a good idea for jquery-ajax-retry. 

Feel free to add this and open a PR. I won't have time for a while to get this working, but I'd definitely accept a contribution.

**Comment by acdha** [comment]
Will do – I was thinking about spinning an improved version of my in-house code out of a project and decided to search for the name I was  thinking about using, so you've already saved me a ton of work ;)

**Comment by kof** [comment]
created a pull request #11 please feel free to review the code

**Comment by johnkpaul** [comment]
Closed with #11
