### ISSUE TITLE
Retrying beyond two times

### ISSUE THREAD

**Issue by ghost** [johnkpaul/jquery-ajax-retry#4]
> Never, never, never give in!

Winston Churchill

---

When I add:

```
console.log(times);
```

inside the `pipeFailRetry` function, the first time, it gives the value of `times`, while the second time, it logs `undefined`.

**Comment by johnkpaul** [comment]
Thank you for your bug report, @html5anchor! This issue should be fixed with my commit.

**Comment by ghost** [comment]
That's more like it. Thank you for the swift action.
